export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const SET_USER_EXT_INFO = 'SET_USER_EXT_INFO'
export const UP_NEW_PLATE_BUILD_SHOW = 'UP_NEW_PLATE_BUILD_SHOW'
export const UP_NEW_PLATE_LAYOUT_SHOW = 'UP_NEW_PLATE_LAYOUT_SHOW'

export const APP_HANDLE_COLLAPSE_CHANGE = 'APP_HANDLE_COLLAPSE_CHANGE'
export const TOGGLE_LAYOUT_CONFIG_VISIBLE = 'TOGGLE_LAYOUT_CONFIG_VISIBLE'

export const INCREMENT = 'INCREMENT'
